"""'new'

Revision ID: f1d451924f25
Revises: 
Create Date: 2019-06-21 17:57:21.375336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d451924f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('children_idents', sa.String(length=255), nullable=True))
    op.drop_column('snapshot_storage', 'children_idents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_storage', sa.Column('children_idents', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('journal', 'children_idents')
    # ### end Alembic commands ###
